namespace Vezel.Novadrop.Interop;

public enum S1ExitReason : uint
{
    S1_EXIT_REASON_SUCCESS = 0x0,
    S1_EXIT_REASON_INVALID_DATA_CENTER = 0x6,
    S1_EXIT_REASON_CONNECTION_DROPPED = 0x8,
    S1_EXIT_REASON_INVALID_AUTHENTICATION_INFO = 0x9,
    S1_EXIT_REASON_OUT_OF_MEMORY = 0xa,
    S1_EXIT_REASON_SHADER_MODEL_3_UNAVAILABLE = 0xc,
    S1_EXIT_REASON_SPEED_HACK_DETECTED = 0x10,
    S1_EXIT_REASON_UNSUPPORTED_VERSION = 0x13,
    S1_EXIT_REASON_ALREADY_ONLINE = 0x106,
}
