# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Package
on:
    push:
        branches:
            - master
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    package:
        if: github.repository == 'vezel-dev/novadrop'
        runs-on: windows-2022
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.6.0
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v3.2.0
            - name: Build project
              run: |
                  dotnet tool restore
                  dotnet build
            - name: Upload GitHub packages
              run: |
                  dotnet gpr push pkg/feed/*.nupkg -k ${{ secrets.GITHUB_TOKEN }}
