# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
    release:
        types:
            - published
permissions:
    contents: read
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
    NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
jobs:
    release:
        if: github.repository == 'vezel-dev/novadrop'
        runs-on: windows-2022
        steps:
            - name: Clone repository
              uses: actions/checkout@v4.1.1
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v4.0.0
            - name: Set up Node.js
              uses: actions/setup-node@v4.0.1
              with:
                  node-version-file: doc/package.json
            - name: Run Cake
              run: |
                  ./cake upload-core-nuget -c Release
            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v4.3.0
              with:
                  name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}-windows-2022-Release
                  path: |
                      out/log
                      out/pkg
                      out/pub
