# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
    release:
        types:
            - published
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    release:
        if: github.repository == 'vezel-dev/novadrop'
        runs-on: windows-2022
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.5.0
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v3.0.3
            - name: Build project
              run: |
                  dotnet tool restore
                  dotnet build -c Release
            - name: Upload NuGet packages
              run: |
                  dotnet nuget push pkg/feed/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
