# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
  release:
    types:
      - published
permissions:
  attestations: write
  contents: read
  id-token: write
defaults:
  run:
    shell: bash
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
jobs:
  release:
    if: github.repository == 'vezel-dev/novadrop'
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up .NET
        uses: actions/setup-dotnet@v4.0.0
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: doc/package.json
      - name: Run Cake
        run: |
          ./cake upload-core-nuget -c Release
      - name: Attest packages
        uses: actions/attest-build-provenance@v1.1.2
        with:
          subject-path: out/pkg/release/*.nupkg
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: |
            out/log
            out/pkg
            out/pub
